ALTER TABLE ACTION ADD INDEX IND_ACT (id_action);

ALTER TABLE ADVENTURE ADD INDEX IND_ADV (id_adventures);

ALTER TABLE ANSWER ADD INDEX IND_ANS (id_answers);

ALTER TABLE CHARACTERS ADD INDEX IND_CHAR (id_character);

ALTER TABLE GAME ADD INDEX IND_GAME (id_game);

ALTER TABLE OPTIONS ADD INDEX IND_OPT (id_options);

ALTER TABLE STEP ADD INDEX IND_STP (id_steps);

ALTER TABLE USER ADD INDEX IND_USER (id_user);
